name: flutter_base_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.4
  firebase_core: ^1.10.0
  firebase_messaging: ^10.0.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.1.2
  fluttertoast: ^8.0.8
  http: ^0.13.3
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
